version: '3'

networks:
  network_1:
  network_2:

services: 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - network_1

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - network_1
      - network_2
  
  redis:
    image: redis:alpine3.16
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - network_2