version: '3'

networks:
  network_1:
  network_2:

services: 
  frontend:
    container_name: frontend
    image: nicolajh/simple-fortune-cookie-frontend
    ports: 
      - "8080:8080"
    networks:
      - network_1

  backend:
    container_name: backend
    image: nicolajh/simple-fortune-cookie-backend
    ports: 
      - "9000:9000"
    depends_on: 
      - redis
    networks:
      - network_1
      - network_2
  
  redis:
    container_name: redis
    image: redis:alpine3.16
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - network_2