apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune
  labels:
    app: fortune
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortune
  template:
    metadata:
      labels:
        app: fortune
    spec:
      containers:
      - name: frontend
        image: nicolajh/simple-fortune-cookie-frontend
      - name: backend
        image:  nicolajh/simple-fortune-cookie-backend
      - name: redis-db
        image: redis

---

apiVersion: v1
kind: Service
metadata:
  name: fortune-service
  labels:
    app: fortune
spec:
  selector:
    app: fortune
  type: NodePort
  ports:
  - name: fortune-service
    protocol: TCP
    port: 8080
    targetPort: 8080
