name: Dev CI
on:
  push:
    branches:
      - dev/**
env:
  GIT_COMMIT: ${{ github.sha }}
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: golang:latest
    steps:
      - name: Clone-down
        uses: actions/checkout@v2
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: |
            .
            !.git
            !.gitgnore
  Build:
    runs-on: ubuntu-latest
    needs: Clone-down
    container: golang:latest
    steps:
      - name: Download Repo
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - run: chmod +x ci/build-app.sh && ci/build-app.sh
        name: Build-app
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path:  |
            .
            !.git
            !.gitgnore
      - name: Upload frontend
        uses: actions/upload-artifact@v2
        with:
          name: build-frontend
          path:  |
            frontend/frontend
            !.git
            !.gitgnore
      - name: Upload backend
        uses: actions/upload-artifact@v2
        with:
          name: build-backend
          path:  |
            backend/backend
            !.git
            !.gitgnore
  Test:
    runs-on: ubuntu-latest
    needs: Build
    container: golang:latest
    steps:
      - name: Download Repo
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - run: chmod +x ci/go-test.sh && ci/go-test.sh
        name: Go-test
  Docker-image:
    runs-on: ubuntu-latest
    needs: [Build, Test]
    steps:
      - name: Download Repo
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Download frontend
        uses: actions/download-artifact@v2
        with:
          name: build-frontend
          path: app/frontend
      - name: Download backend
        uses: actions/download-artifact@v2
        with:
          name: build-backend
          path: app/backend
      - name: Build docker backend
        run: chmod +x ci/build-docker-backend.sh && ci/build-docker-backend.sh
      - name: Build docker frontend
        run: chmod +x ci/build-docker-frontend.sh && ci/build-docker-frontend.sh
  Deploy:
    runs-on: dev-runner
    needs: [Docker-image]
    steps:
      - name: Download Repo
        uses: actions/download-artifact@v2
        with: 
          name: code
          path: .
      - name: Deploy to kubernetes
        uses: Azure/k8s-deploy@v3.1
        with:
          namespace: 'student17'
          manifests: |
              ci